# Generated by Django 5.2 on 2025-05-06 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0002_remove_category_sub_category_sub_category_category'),
        ('recs', '0004_alter_record_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recs.type', verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
