# Generated by Django 5.2 on 2025-05-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='created_at',
            field=models.DateTimeField(verbose_name='Дата создания записи'),
        ),
    ]
