# Generated by Django 5.2 on 2025-05-06 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0002_remove_category_sub_category_sub_category_category'),
        ('recs', '0002_alter_record_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categorys.sub_category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
